### ISSUE TITLE
ImportError on Ubuntu 18.04

### ISSUE THREAD

**Issue by cpiscos** [apache/arrow#2213]
I installed pyarrow from conda-forge and I'm getting this error on import:

```
>>> import pyarrow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chris/miniconda3/envs/ai/lib/python3.6/site-packages/pyarrow/__init__.py", line 47, in <module>
    from pyarrow.lib import cpu_count, set_cpu_count
ImportError: /home/chris/miniconda3/envs/ai/lib/python3.6/site-packages/pyarrow/../../../libparquet.so.1: undefined symbol: _ZNK5boost16re_detail_10650131cpp_regex_traits_implementationIcE9transformEPKcS4_
```

**Comment by kszucs** [comment]
Duplicate of https://issues.apache.org/jira/browse/ARROW-2783

**Comment by xhochy** [comment]
This should be fixed now, please try to reinstall `arrow-cpp`, `parquet-cpp` and `pyarrow` from `conda-forge`.

**Comment by cpiscos** [comment]
Can confirmed it's fixed. Thank you!

**Comment by sephib** [comment]
Hi,
I'm still having the same problem.
I'm working on `dask_yarn` and need to read hdfs files. I have installed  `arrow-cpp 0.10.0` and `parquet-cpp 1.5.0.pre`, but when I try to import pyarrow I get the following error: 

```
> ---------------------------------------------------------------------------
> ImportError                               Traceback (most recent call last)
> <ipython-input-2-852643f3aad4> in <module>()
> ----> 1 import pyarrow as pa
> 
> ~/anaconda3/lib/python3.6/site-packages/pyarrow/__init__.py in <module>()
>      58 
>      59 
> ---> 60 from pyarrow.lib import cpu_count, set_cpu_count
>      61 from pyarrow.lib import (null, bool_,
>      62                          int8, int16, int32, int64,
> 
> ImportError: /home/fcuser/anaconda3/lib/python3.6/site-packages/pyarrow/../../../libparquet.so.1: undefined symbol: _ZN5boost13match_resultsIN9__gnu_cxx17__normal_iteratorIPKcSsEESaINS_9sub_matchIS5_EEEE12maybe_assignERKS9_
> 
``` 
I reinstalled the the packages put I'm still getting the same error
`conda install --offline -f arrow-cpp-0.10.0-py36h70250a7_0.tar.bz2 parquet-cpp-1.5.0.pre-h83d4a3d_0.tar.bz2`

Any suggestions?

**Comment by sephib** [comment]
Hi,
Thank you very much for your reply and solution
I updated all the packages to be from `conda-forge`  and it workes now.
Thx

**Comment by rstuckey** [comment]
This is really frustrating. I'm getting the same error as @cpiscos , but cannot reinstall libboost from conda-forge (does it even exist on that channel?).
```
(testenv) $ conda install --channel conda-forge boost boost-cpp libboost pyarrow
Solving environment: done

## Package Plan ##

  environment location: /opt/anaconda3/envs/testenv

  added / updated specs: 
    - boost
    - boost-cpp
    - libboost
    - pyarrow


The following NEW packages will be INSTALLED:

    arrow-cpp: 0.11.0-py36hccec0d8_0 conda-forge
    boost:     1.67.0-py36h3e44d54_0 conda-forge
    boost-cpp: 1.67.0-h3a22d5f_0     conda-forge
    libboost:  1.67.0-h46d08c1_4     defaults   
    pyarrow:   0.11.0-py36hfc679d8_0 conda-forge
```
Installing all but libboost results in the following error:
```
(testenv) $ python
Python 3.6.6 | packaged by conda-forge | (default, Oct 12 2018, 14:08:43) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyarrow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/envs/testenv/lib/python3.6/site-packages/pyarrow/__init__.py", line 54, in <module>
    from pyarrow.lib import cpu_count, set_cpu_count
ImportError: libboost_system.so.1.67.0: cannot open shared object file: No such file or directory
>>> 
```
Any advice would be appreciated.

**Comment by wesm** [comment]
Can you remove `libboost`? Having that and `boost-cpp` is going to cause you these problems

**Comment by rstuckey** [comment]
Yep, I think that's it. Looks like `libhdfs3` was restricting boost:
```
(testenv) $ /opt/anaconda3/bin/conda install --channel conda-forge --override-channels pyarrow=0.11.0
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - libhdfs3 -> boost-cpp=1.64
  - pyarrow=0.11.0 -> arrow-cpp=0.11.0 -> boost-cpp[version='>=1.67.0,<1.67.1.0a0']
  - pyarrow=0.11.0 -> arrow-cpp=0.11.0 -> numpy[version='>=1.14,<2.0a0']
Use "conda info <package>" to see the dependencies for each package.

(testenv) $ /opt/anaconda3/bin/conda uninstall hdfs3
Solving environment: done

## Package Plan ##

  environment location: /opt/anaconda3/envs/testenv

  removed specs: 
    - hdfs3

The following packages will be REMOVED:

    hdfs3: 0.3.0-py36_0 conda-forge

Proceed ([y]/n)? 

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(testenv) $ /opt/anaconda3/bin/conda install --channel conda-forge --override-channels pyarrow=0.11.0
Solving environment: done

## Package Plan ##

  environment location: /opt/anaconda3/envs/testenv

  added / updated specs: 
    - pyarrow=0.11.0


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    boost-cpp-1.67.0           |       h3a22d5f_0        19.7 MB  conda-forge
    boost-1.67.0               |   py36h3e44d54_0         316 KB  conda-forge
    pyarrow-0.11.0             |   py36hfc679d8_0         2.0 MB  conda-forge
    parquet-cpp-1.2.0.pre      |                0         1.6 MB  conda-forge
    arrow-cpp-0.11.0           |   py36hccec0d8_0         6.1 MB  conda-forge
    ------------------------------------------------------------
                                           Total:        29.7 MB

The following packages will be REMOVED:

    libhdfs3:    2.3-3                conda-forge

The following packages will be UPDATED:

    arrow-cpp:   0.9.0-py36h1ae9da6_7 conda-forge --> 0.11.0-py36hccec0d8_0 conda-forge
    boost:       1.66.0-py36_1        conda-forge --> 1.67.0-py36h3e44d54_0 conda-forge
    boost-cpp:   1.66.0-1             conda-forge --> 1.67.0-h3a22d5f_0     conda-forge
    pyarrow:     0.9.0-py36hfc679d8_2 conda-forge --> 0.11.0-py36hfc679d8_0 conda-forge

The following packages will be DOWNGRADED:

    parquet-cpp: 1.4.0-h83d4a3d_1     conda-forge --> 1.2.0.pre-0           conda-forge

Proceed ([y]/n)? 


Downloading and Extracting Packages
boost-cpp-1.67.0     | 19.7 MB   | ######################################################### | 100% 
boost-1.67.0         | 316 KB    | ######################################################### | 100% 
pyarrow-0.11.0       | 2.0 MB    | ######################################################### | 100% 
parquet-cpp-1.2.0.pr | 1.6 MB    | ######################################################### | 100% 
arrow-cpp-0.11.0     | 6.1 MB    | ######################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(testenv) $ python
Python 3.6.6 | packaged by conda-forge | (default, Oct 12 2018, 14:08:43) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyarrow
>>> 
```
Thanks again!

**Comment by xhochy** [comment]
@wesm This parquet-cpp version is one with a more open `arrow-cpp` pinning. Newer `parquet-cpp` version pin `arrow-cpp` more exactly. The correct behaviour would be to uninstall `parquet-cpp`.

**Comment by wesm** [comment]
I think the correct option here is to pin the parquet-cpp metapackage in https://github.com/conda-forge/pyarrow-feedstock/blob/master/recipe/meta.yaml#L33. This will cause other versions to be uninstalled I think

**Comment by xhochy** [comment]
That would make `parquet-cpp` a dependency again, do we want this?

**Comment by wesm** [comment]
It's an empty metapackage, I thought that was the idea anyway

**Comment by wesm** [comment]
I added here in the PR for 0.11.1 https://github.com/conda-forge/pyarrow-feedstock/pull/59/commits/74c3fba556c5076eea062639215367faf475e10f

**Comment by kszucs** [comment]
I don't know why parquet-cpp gets installed, it's not a dependency arrow-cpp or pyarrow.

**Comment by kszucs** [comment]
The most safe choice for now is indeed to pin parquet-cpp in pyarrow. However We should ask a forge developer about correctly handling this scenario.

**Comment by kszucs** [comment]
Conda now updates correctly:

```bash
$ conda update pyarrow

Solving environment: done

## Package Plan ##

  environment location: /Users/krisz/.conda/envs/test

  added / updated specs:
    - pyarrow


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pyarrow-0.11.1             |   py36hfc679d8_0         1.9 MB  conda-forge
    parquet-cpp-1.5.1          |                1           3 KB  conda-forge
    arrow-cpp-0.11.1           |   py36h3bd774a_0         4.9 MB  conda-forge
    ------------------------------------------------------------
                                           Total:         6.7 MB

The following packages will be UPDATED:

    arrow-cpp:   0.10.0-py36h70250a7_0 conda-forge --> 0.11.1-py36h3bd774a_0 conda-forge
    boost-cpp:   1.67.0-h3a22d5f_0     conda-forge --> 1.68.0-h3a22d5f_0     conda-forge
    parquet-cpp: 1.5.0.pre-h83d4a3d_0  conda-forge --> 1.5.1-1               conda-forge
    pyarrow:     0.10.0-py36hfc679d8_0 conda-forge --> 0.11.1-py36hfc679d8_0 conda-forge
```

**Comment by wesm** [comment]
That's great, thanks @kszucs!

**Comment by jacksonloper** [comment]
I think this is still broken-ish.  The following dockerfile results in a pyarrow installation that is broken with the `_ZNK5arrow5Field8ToStringB5cxx11Ev` problem:

```
FROM jupyter/datascience-notebook
RUN conda install -y -c conda-forge -c pytorch opencv tensorflow graphviz tqdm keras numba numpy tqdm pythreejs 
```

**Comment by wesm** [comment]
@jacksonloper can we discuss this issue somewhere else, like on the ASF JIRA? I'm not sure where the problem is but we should identify the root cause and open an issue in the upstream project (e.g. if one of these other projects is causing the issue) or fix our packaging stuff otherwise

**Comment by jacksonloper** [comment]
Not a member of ASF JIRA.  But I also probably won't be much help.  Just letting you know its still broken  :).  Happy to create a more barebones broken-case, from a vanilla ubuntu docker or something if you want.

**Comment by wesm** [comment]
Can you create an account on https://issues.apache.org/jira and open a JIRA issue?

**Comment by wesm** [comment]
It looks like this is https://issues.apache.org/jira/browse/ARROW-4809. I'll copy-paste your repro there

**Comment by jacksonloper** [comment]
Awesome thanks
