### ISSUE TITLE
Fails to build Go project for Windows x86

### ISSUE THREAD

**Issue by abemedia** [apache/arrow#34784]
### Describe the bug, including details regarding any error messages, version, and platform.

When compiling a Go project using `github.com/apache/arrow/go/v10` v10.0.1 on Go 1.19.3 windows/amd64 with `GOOS=windows` and `GOARCH=386` I get the following errors:
```
failed to build for windows_386: exit status 2: # github.com/apache/arrow/go/v10/internal/utils
..\..\..\go\pkg\mod\github.com\apache\arrow\go\v10@v10.0.1\internal\utils\transpose_ints_def.go:76:4: undefined: TransposeInt8Int8
..\..\..\go\pkg\mod\github.com\apache\arrow\go\v10@v10.0.1\internal\utils\transpose_ints_def.go:78:4: undefined: TransposeInt8Int16
..\..\..\go\pkg\mod\github.com\apache\arrow\go\v10@v10.0.1\internal\utils\transpose_ints_def.go:80:4: undefined: TransposeInt8Int32
..\..\..\go\pkg\mod\github.com\apache\arrow\go\v10@v10.0.1\internal\utils\transpose_ints_def.go:82:4: undefined: TransposeInt8Int64
..\..\..\go\pkg\mod\github.com\apache\arrow\go\v10@v10.0.1\internal\utils\transpose_ints_def.go:84:4: undefined: TransposeInt8Uint8
..\..\..\go\pkg\mod\github.com\apache\arrow\go\v10@v10.0.1\internal\utils\transpose_ints_def.go:86:4: undefined: TransposeInt8Uint16
..\..\..\go\pkg\mod\github.com\apache\arrow\go\v10@v10.0.1\internal\utils\transpose_ints_def.go:88:4: undefined: TransposeInt8Uint32
..\..\..\go\pkg\mod\github.com\apache\arrow\go\v10@v10.0.1\internal\utils\transpose_ints_def.go:90:4: undefined: TransposeInt8Uint64
..\..\..\go\pkg\mod\github.com\apache\arrow\go\v10@v10.0.1\internal\utils\transpose_ints_def.go:95:4: undefined: TransposeInt16Int8
..\..\..\go\pkg\mod\github.com\apache\arrow\go\v10@v10.0.1\internal\utils\transpose_ints_def.go:97:4: undefined: TransposeInt16Int16
..\..\..\go\pkg\mod\github.com\apache\arrow\go\v10@v10.0.1\internal\utils\transpose_ints_def.go:97:4: too many errors
```

I tried using the build tag `noasm` but then I get the following error:

```
failed to build for windows_386: exit status 2: # github.com/apache/arrow/go/v10/arrow/array
..\..\..\go\pkg\mod\github.com\apache\arrow\go\v10@v10.0.1\arrow\array\dictionary.go:1499:22: math.MaxUint32 (untyped int constant 4294967295) overflows int
```

### Component(s)

Go

**Comment by zeroshade** [comment]
This should be addressed and fixed with #34647 can you upgrade to v12@latest and give it a try to confirm? Assuming that fixes this too, the fix would go out with the v12 release in a few weeks

**Comment by maxcoulombe** [comment]
Hi, I tried to use `[go/v12.0.0](https://github.com/apache/arrow/releases/tag/go%2Fv12.0.0)` as suggested and it does fix the undefined errors, but we still get the overflow error:
`Error: ../../../go/pkg/mod/github.com/apache/arrow/go/v12@v12.0.0/arrow/compute/internal/exec/utils.go:247:18: cannot use math.MaxInt64 (untyped int constant 9223372036854775807) as int value in assignment (overflows)`

Any workaround or fix in progress?

**Comment by zeroshade** [comment]
@maxcoulombe I've put a fix up via PR, as we are looking at releasing a v12.0.1 patch release, I'll see if I can get the fix into that release.
