### ISSUE TITLE
[Go] IPC Writer encodes sliced list arrays incorrectly. 

### ISSUE THREAD

**Issue by thorfour** [apache/arrow#35621]
### Describe the bug, including details regarding any error messages, version, and platform.

When you create a record with a list column, if you slice that array and then try and encode the slices with the IPC writer, it produces incorrect results when read back from the IPC format. 

It appears to incorrectly address the offsets of a slice if the slice has a non-zero offset.  Below is an example test that fails because the second slice returns the first two lists after IPC encoding instead of the expected last two lists.

```
func Test_Arrow_SlicedList(t *testing.T) {
    schema := arrow.NewSchema([]arrow.Field{
        {
            Name: "letters",
            Type: arrow.ListOf(&arrow.StringType{}),
        },
    }, nil)

    rb := array.NewRecordBuilder(memory.NewGoAllocator(), schema)

    lb := rb.Field(0).(*array.ListBuilder)
    sb := lb.ValueBuilder().(*array.StringBuilder)
    lb.Append(true)
    sb.Append("a")
    sb.Append("b")
    sb.Append("c")
    lb.Append(true)
    sb.Append("d")
    sb.Append("e")
    sb.Append("f")
    lb.Append(true)
    sb.Append("g")
    sb.Append("h")
    sb.Append("i")

    r := rb.NewRecord()

    r0 := r.NewSlice(0, 1)
    r1 := r.NewSlice(1, 3)

    b := &bytes.Buffer{}
    w := ipc.NewWriter(b, ipc.WithSchema(r.Schema()))
    require.NoError(t, w.Write(r0))
    require.NoError(t, w.Write(r1))
    require.NoError(t, w.Close())

    rdr, err := ipc.NewReader(b)
    require.NoError(t, err)

    rdr.Next()
    read0 := rdr.Record()
    read0.Retain()
    rdr.Next()
    read1 := rdr.Record()

    require.True(t, array.RecordEqual(r0, read0))
    require.True(t, array.RecordEqual(r1, read1))
}
```

```
thor@thors-MacBook-Pro frostdb % go test -v -run SlicedList
=== RUN   Test_Arrow_SlicedList
    table_test.go:1773:
        	Error Trace:	/Users/thor/go/src/github.com/polarsignals/frostdb/table_test.go:1773
        	Error:      	Should be true
        	Test:       	Test_Arrow_SlicedList
--- FAIL: Test_Arrow_SlicedList (0.00s)
```

### Component(s)

Go

**Comment by zeroshade** [comment]
@thorfour which version of Arrow are you using here? I ask because issues with IPC slicing list/map arrays were brought up in #14780 and addressed by #14793. That fix went out with Arrow v11 so if you're using an earlier version than Go Arrow v11, can you try upgrading first and seeing if you can still reproduce the failure in v11 or v12?

**Comment by thorfour** [comment]
Wow thank you for pointing that out! I thought I had updated my version, but apparently my go.mod was incorrect. It's working as expected with the latest. Thank you so much!

**Comment by thorfour** [comment]
I'm reopening this because I discovered that the bug still exists for `LargeLists` but verified that it indeed worked as expected for regular lists

**Comment by thorfour** [comment]
Okay, closing again because it looks like that was fixed in v13 now.
