### ISSUE TITLE
[Website][Docs] Version selector on the published docs for 13.0.0 seems broken

### ISSUE THREAD

**Issue by raulcd** [apache/arrow#37357]
### Describe the bug, including details regarding any error messages, version, and platform.

There seems to be something wrong with the version selector for the docs (https://arrow.apache.org/docs/index.html):
![image](https://github.com/apache/arrow/assets/639755/c330e1c2-d6b8-47cd-84ac-635581de9b46)
Release 13.0.0 is released and should appear as stable.
If I click on the `12.0.0(stable)` version selector, I get the `13.0.0` docs but there is no link to `12.0.0` on the selector apart from that.

### Component(s)

Documentation, Website

**Comment by raulcd** [comment]
@thisisnic @jorisvandenbossche @AlenkaF I know you worked on this in the past (or something related). Any idea of what happened?

**Comment by AlenkaF** [comment]
One thing I noticed is that the `versions.json` file was not updated here: https://arrow.apache.org/docs/_static/versions.json and this is the file from where the data gets pulled into the [version warnings](https://github.com/apache/arrow-site/blob/2742aa4adabb7b811115f1b7ee1f163788337f21/docs/_static/versionwarning.js#L21) and I think also to the [version switcher](https://github.com/apache/arrow/blob/b9453a2a33e935e26dc8358846ad671aefdcb4d0/docs/source/conf.py#L297).

It just changed now though =)

**Comment by AlenkaF** [comment]
And the issue on the site is fixed ...

**Comment by jorisvandenbossche** [comment]
Do a "hard" refresh of the page. The versions.json file is cached by your browser, and so still shows the old versions. But the file itself is correctly updated, I think: https://github.com/apache/arrow-site/blob/asf-site/docs/_static/versions.json

**Comment by raulcd** [comment]
Oh! I see, this is cached and we require a hard refresh. I am wondering if we can ask INFRA if they can set some headers for non-caching on some files like this one or if it is not worth it.

**Comment by kou** [comment]
If we want to disable caching, we can use `fetch()`'s `cache: "no-cache"` option: https://developer.mozilla.org/en-US/docs/Web/API/fetch

Note that we're using jQuery's `$.getJSON()` not `fetch()`:
https://github.com/apache/arrow/blob/c9275200081ee8b245c974e0cbe854df5ab1e3c0/docs/source/_static/versionwarning.js#L21

**Comment by jorisvandenbossche** [comment]
I think the exact implementation is being changed in https://github.com/apache/arrow/pull/36591 (now using the sphinx theme's upstream one), so if we want to look into it, might be better to do that afterwards.

I also don't know if we _want_ to disable caching, as for most of the time, the caching actually is beneficial (although I don't know how important this is, given it's a small file)

**Comment by kou** [comment]
I think that we don't need to disable cache because this will be fixed (the cache will be expired) eventually.

**Comment by raulcd** [comment]
That makes sense to me. I am closing the issue.
