### ISSUE TITLE
[Docs][R] Contrast issues in the navbar on the website

### ISSUE THREAD

**Issue by etiennebacher** [apache/arrow#40591]
### Describe the bug, including details regarding any error messages, version, and platform.

Hello, this is a minor detail but it's hard to read some of the text in the navbar on the website, specifically the version number (next to "Arrow R Package") and the text in the search box:

![image](https://github.com/apache/arrow/assets/52219252/45c394e8-ab26-4b24-97c6-af66d549012a)

I also think the text for section names ("Get started", etc.) could be a bit lighter. I use Firefox (current is 123.0.1) in case it's a browser-specific thing.

### Component(s)

Documentation, R

**Comment by amoeba** [comment]
Hey @etiennebacher, I see what you see so I agree with the feedback. Would you be interested in looking into this? If not, let me know and I can work on it.

**Comment by etiennebacher** [comment]
Yes, I can make a PR for this

**Comment by amoeba** [comment]
Issue resolved by pull request 40610
https://github.com/apache/arrow/pull/40610

**Comment by etiennebacher** [comment]
Looks like this is not resolved, here's what I have at https://arrow.apache.org/docs/r/ (basically the same as in the original post):

![image](https://github.com/apache/arrow/assets/52219252/c89f70dd-c62b-4aa0-8b95-838686b193fd)

Is there a development version of this site? I also don't see which github action takes care of the pkgdown workflow.

**Comment by amoeba** [comment]
Hi @etiennebacher, sorry. Resolving this is a bit confusing. What you see on https://arrow.apache.org is managed over on https://github.com/apache/arrow-site which builds off of what's in this repo. The changes aren't automatically propagated but should be picked up when we release Arrow 16.

**Comment by etiennebacher** [comment]
I see, thanks for the explanation
