### ISSUE TITLE
[Go][FlightRPC] Stateless prepared statements don't actually work

### ISSUE THREAD

**Issue by lidavidm** [apache/arrow#41427]
https://github.com/erratic-pattern/arrow/blob/af0765eebfc67579b369e80b5c3d600b580cfcf8/go/arrow/flight/flightsql/client.go#L1110-L1141

We capture the new value, but we continue to use the old `desc` in the final call to `getFlightInfo`

_Originally posted by @lidavidm in https://github.com/apache/arrow/issues/40311#issuecomment-2081943885_

**Comment by lidavidm** [comment]
Issue resolved by pull request 41428
https://github.com/apache/arrow/pull/41428

**Comment by alamb** [comment]
Thank you @lidavidm

**Comment by matthewmturner** [comment]
Cross posting here from a comment I made on the PR for this.

"FYI we are still seeing having issues with stateless prepared statements from go. It seems to be working from a rust client but something going on with the deserialization of the handle where the data in handle is ending up unknown fields of DoPutPreparedStatementResult instead of prepared_statement_handle.

It's possible that the issue is actually on our side but given that the rust client worked without issue I'm inclined to think its on the go client side. I am looking into it, but wanted to raise it here as well."
