### ISSUE TITLE
[CI][C++] Recurrent failures downloading ORC from download.apache.org

### ISSUE THREAD

**Issue by pitrou** [apache/arrow#44985]
### Describe the bug, including details regarding any error messages, version, and platform.

We have recently starting to see very frequent download errors for the ORC library. Example:
https://github.com/apache/arrow/actions/runs/12245621761/job/34159883827
```
-- Downloading...
   dst='/Users/runner/work/arrow/arrow/build/cpp/_deps/orc-build/orc-format_ep-prefix/src/orc-format-1.0.0.tar.gz'
   timeout='none'
   inactivity timeout='none'
-- Using src='https://archive.apache.org/dist/orc/orc-format-1.0.0/orc-format-1.0.0.tar.gz'
-- Retrying...
-- Using src='https://archive.apache.org/dist/orc/orc-format-1.0.0/orc-format-1.0.0.tar.gz'
-- Retry after 5 seconds (attempt #2) ...
-- Using src='https://archive.apache.org/dist/orc/orc-format-1.0.0/orc-format-1.0.0.tar.gz'
-- Retry after 5 seconds (attempt #3) ...
-- Using src='https://archive.apache.org/dist/orc/orc-format-1.0.0/orc-format-1.0.0.tar.gz'
-- Retry after 15 seconds (attempt #4) ...
-- Using src='https://archive.apache.org/dist/orc/orc-format-1.0.0/orc-format-1.0.0.tar.gz'
-- Retry after 60 seconds (attempt #5) ...
-- Using src='https://archive.apache.org/dist/orc/orc-format-1.0.0/orc-format-1.0.0.tar.gz'
CMake Error at orc-format_ep-stamp/download-orc-format_ep.cmake:163 (message):
  Each download failed!

    error: downloading 'https://archive.apache.org/dist/orc/orc-format-1.0.0/orc-format-1.0.0.tar.gz' failed
          status_code: 28
          status_string: "Timeout was reached"
          log:
          --- LOG BEGIN ---
          Host archive.apache.org:443 was resolved.
```

https://archive.apache.org/ indexes all past releases but discourages heavy use. We're probably hitting a rate limiter and being temporarily banned because of that.

### Component(s)

C++, Continuous Integration

**Comment by pitrou** [comment]
Issue resolved by pull request 44977
https://github.com/apache/arrow/pull/44977

**Comment by NickCrews** [comment]
@pitrou I think we are still getting hit by this (or similar) in https://github.com/apache/arrow/actions/runs/12313812270/job/34368638458?pr=43782?

**Comment by pitrou** [comment]
@NickCrews Yes, this will be fully solved with the next ORC release (see https://github.com/apache/orc/pull/1830)
