### ISSUE TITLE
[C++] AMD64 macOS 13 C++ and ARM64 macOS 14 C++ are failing due to no type named 'int64' in namespace 'google::protobuf'

### ISSUE THREAD

**Issue by vic-tsang** [apache/arrow#47399]
### Describe the bug, including details regarding any error messages, version, and platform.

Currently the C++ github build workflow fails for macOS13 and macOS 14 
```

[101/1141] Building CXX object _deps/orc-build/c++/src/CMakeFiles/orc.dir/io/OutputStream.cc.o
FAILED: [code=1] _deps/orc-build/c++/src/CMakeFiles/orc.dir/io/OutputStream.cc.o 
/usr/local/bin/ccache /usr/bin/c++ -DARROW_HAVE_RUNTIME_AVX2 -DARROW_HAVE_RUNTIME_AVX512 -DARROW_HAVE_RUNTIME_BMI2 -DARROW_HAVE_RUNTIME_SSE4_2 -DARROW_HAVE_SSE4_2 -DENABLE_METRICS=0 -DPROTOBUF_USE_DLLS -I/Users/runner/work/arrow/arrow/build/cpp/_deps/orc-build/c++/include -I/Users/runner/work/arrow/arrow/build/cpp/_deps/orc-src/c++/include -I/Users/runner/work/arrow/arrow/build/cpp/_deps/orc-build/c++/src -I/Users/runner/work/arrow/arrow/build/cpp/_deps/orc-src/c++/src -isystem /usr/local/opt/lz4/include -Qunused-arguments -fcolor-diagnostics -std=c++17 -Wall -Wextra -std=c++17 -Wall -Wextra -O0 -g -fno-omit-frame-pointer -std=c++17 -fPIC -MD -MT _deps/orc-build/c++/src/CMakeFiles/orc.dir/io/OutputStream.cc.o -MF _deps/orc-build/c++/src/CMakeFiles/orc.dir/io/OutputStream.cc.o.d -o _deps/orc-build/c++/src/CMakeFiles/orc.dir/io/OutputStream.cc.o -c /Users/runner/work/arrow/arrow/build/cpp/_deps/orc-src/c++/src/io/OutputStream.cc
In file included from /Users/runner/work/arrow/arrow/build/cpp/_deps/orc-src/c++/src/io/OutputStream.cc:19:
/Users/runner/work/arrow/arrow/build/cpp/_deps/orc-src/c++/src/io/OutputStream.hh:64:31: error: no type named 'int64' in namespace 'google::protobuf'
    virtual google::protobuf::int64 ByteCount() const override;
            ~~~~~~~~~~~~~~~~~~^
/Users/runner/work/arrow/arrow/build/cpp/_deps/orc-src/c++/src/io/OutputStream.cc:68:21: error: no type named 'int64' in namespace 'google::protobuf'
  google::protobuf::int64 BufferedOutputStream::ByteCount() const {
  ~~~~~~~~~~~~~~~~~~^
/Users/runner/work/arrow/arrow/build/cpp/_deps/orc-src/c++/src/io/OutputStream.cc:69:42: error: no type named 'int64' in namespace 'google::protobuf'
    return static_cast<google::protobuf::int64>(dataBuffer_->size());
                       ~~~~~~~~~~~~~~~~~~^
3 errors generated. 
```

Ref: https://github.com/apache/arrow/actions/runs/17132965345/job/48601758287

### Component(s)

C++

**Comment by kou** [comment]
We need https://github.com/apache/orc/pull/2357 .

**Comment by raulcd** [comment]
Issue resolved by pull request 47408
https://github.com/apache/arrow/pull/47408

**Comment by barracuda156** [comment]
@raulcd @kou When was it fixed? It is still broken in 22.0.0.
```
[33/490] /opt/local/bin/g++-mp-14 -DARROW_EXTRA_ERROR_CONTEXT -DARROW_WITH_TIMING_TESTS -DENABLE_METRICS=0 -DPROTOBUF_USE_DLLS -I/opt/local/var/macports/build/apache-arrow-c20e709a/work/build/_deps/orc-build/c++/include -I/opt/local/var/macports/build/apache-arrow-c20e709a/work/build/_deps/orc-src/c++/include -I/opt/local/var/macports/build/apache-arrow-c20e709a/work/build/_deps/orc-build/c++/src -I/opt/local/var/macports/build/apache-arrow-c20e709a/work/build/_deps/orc-src/c++/src -isystem /opt/local/include -pipe -I/opt/local/libexec/openssl3/include -I/opt/local/libexec/boost/1.81/include -Os -DNDEBUG -I/opt/local/libexec/openssl3/include -isystem/opt/local/include/LegacySupport -I/opt/local/libexec/boost/1.81/include -isystem/opt/local/include -D_GLIBCXX_USE_CXX11_ABI=0 -fdiagnostics-color=always -std=c++17 -Wall -Wextra -std=c++17 -Wall -Wextra -O3 -DNDEBUG -std=c++17 -arch ppc -mmacosx-version-min=10.6 -fPIC -MD -MT _deps/orc-build/c++/src/CMakeFiles/orc.dir/io/InputStream.cc.o -MF _deps/orc-build/c++/src/CMakeFiles/orc.dir/io/InputStream.cc.o.d -o _deps/orc-build/c++/src/CMakeFiles/orc.dir/io/InputStream.cc.o -c /opt/local/var/macports/build/apache-arrow-c20e709a/work/build/_deps/orc-src/c++/src/io/InputStream.cc
FAILED: [code=1] _deps/orc-build/c++/src/CMakeFiles/orc.dir/io/InputStream.cc.o 
/opt/local/bin/g++-mp-14 -DARROW_EXTRA_ERROR_CONTEXT -DARROW_WITH_TIMING_TESTS -DENABLE_METRICS=0 -DPROTOBUF_USE_DLLS -I/opt/local/var/macports/build/apache-arrow-c20e709a/work/build/_deps/orc-build/c++/include -I/opt/local/var/macports/build/apache-arrow-c20e709a/work/build/_deps/orc-src/c++/include -I/opt/local/var/macports/build/apache-arrow-c20e709a/work/build/_deps/orc-build/c++/src -I/opt/local/var/macports/build/apache-arrow-c20e709a/work/build/_deps/orc-src/c++/src -isystem /opt/local/include -pipe -I/opt/local/libexec/openssl3/include -I/opt/local/libexec/boost/1.81/include -Os -DNDEBUG -I/opt/local/libexec/openssl3/include -isystem/opt/local/include/LegacySupport -I/opt/local/libexec/boost/1.81/include -isystem/opt/local/include -D_GLIBCXX_USE_CXX11_ABI=0 -fdiagnostics-color=always -std=c++17 -Wall -Wextra -std=c++17 -Wall -Wextra -O3 -DNDEBUG -std=c++17 -arch ppc -mmacosx-version-min=10.6 -fPIC -MD -MT _deps/orc-build/c++/src/CMakeFiles/orc.dir/io/InputStream.cc.o -MF _deps/orc-build/c++/src/CMakeFiles/orc.dir/io/InputStream.cc.o.d -o _deps/orc-build/c++/src/CMakeFiles/orc.dir/io/InputStream.cc.o -c /opt/local/var/macports/build/apache-arrow-c20e709a/work/build/_deps/orc-src/c++/src/io/InputStream.cc
In file included from /opt/local/var/macports/build/apache-arrow-c20e709a/work/build/_deps/orc-src/c++/src/io/InputStream.cc:19:
/opt/local/var/macports/build/apache-arrow-c20e709a/work/build/_deps/orc-src/c++/src/io/InputStream.hh:75:31: error: 'int64' in namespace 'google::protobuf' does not name a type
   75 |     virtual google::protobuf::int64 ByteCount() const override;
      |                               ^~~~~
/opt/local/var/macports/build/apache-arrow-c20e709a/work/build/_deps/orc-src/c++/src/io/InputStream.cc:115:21: error: 'int64' in namespace 'google::protobuf' does not name a type
  115 |   google::protobuf::int64 SeekableArrayInputStream::ByteCount() const {
      |                     ^~~~~
[34/490] cd /opt/local/var/macports/build/apache-arrow-c20e709a/work/build/google_cloud_cpp_ep-prefix/src/google_cloud_cpp_ep-build && /opt/local/bin/cmake -P /opt/local/var/macports/build/apache-arrow-c20e709a/work/build/google_cloud_cpp_ep-prefix/src/google_cloud_cpp_ep-stamp/google_cloud_cpp_ep-configure-Release.cmake && /opt/local/bin/cmake -E touch /opt/local/var/macports/build/apache-arrow-c20e709a/work/build/google_cloud_cpp_ep-prefix/src/google_cloud_cpp_ep-stamp/google_cloud_cpp_ep-configure
ninja: build stopped: subcommand failed.
Command failed:  cd "/opt/local/var/macports/build/apache-arrow-c20e709a/work/build" && ninja -j2 all -j2 -v 
Exit code: 1
Error: Failed to build apache-arrow: command execution failed
```

**Comment by kou** [comment]
Is it really 22.0.0? Could you share full build log?

**Comment by barracuda156** [comment]
@kou For some reason the patch was not applied by the build. I added an extra condition on `if(APPLE)` into relevant CMake module, and that fixed the build (i.e. existing patch for Orc was applied then). No idea why existing condition does not work, I got `protobuf` 31.1 currently.

**Comment by kou** [comment]
Ah, `32.0` in https://github.com/apache/arrow/blob/apache-arrow-22.0.0/cpp/cmake_modules/ThirdpartyToolchain.cmake#L4624 should be `22.0`.
