### ISSUE TITLE
PyArrow v22.0 assumes Pandas DataFrame attrs are serializable

### ISSUE THREAD

**Issue by aiudirog** [apache/arrow#47966]
### Describe the bug, including details regarding any error messages, version, and platform.

https://github.com/apache/arrow/commit/0d72f7e8f33a79ced28f42017bf07910c85c6d74 automatically includes the Pandas DataFrame attrs in the common metadata, however it doesn't handle the case where values are not JSON serializable.

Reproducing example:
```python
from datetime import datetime

import pandas as pd
import pyarrow as pa

df = pd.DataFrame({'x': [1, 2, 3]})
df.attrs['timestamp'] = datetime.fromisoformat('2025-10-27T11:12:13')

pa.table(df)
```

Output:
```python-traceback
Traceback (most recent call last):
  File "/venv/python312/Lib/site-packages/IPython/core/interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-11-5bf84f5fe292>", line 9, in <module>
    pa.table(df)
  File "pyarrow/table.pxi", line 6216, in pyarrow.lib.table
  File "pyarrow/table.pxi", line 4795, in pyarrow.lib.Table.from_pandas
  File "/venv/python312/Lib/site-packages/pyarrow/pandas_compat.py", line 663, in dataframe_to_arrays
    pandas_metadata = construct_metadata(
                      ^^^^^^^^^^^^^^^^^^^
  File "/venv/python312/Lib/site-packages/pyarrow/pandas_compat.py", line 281, in construct_metadata
    b'pandas': json.dumps({
               ^^^^^^^^^^^^
  File "/venv/python312/Lib/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/python312/Lib/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/python312/Lib/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/venv/python312/Lib/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable
```

Versions Used:
- CPython: 3.12.7
- PyArrow: 22.0.0
- Pandas: 2.3.3

Platforms:
- Debian Linux
- Windows 11

### Component(s)

Python

**Comment by pitrou** [comment]
Ouch! This seems like an important regression. @rok @AlenkaF @raulcd Perhaps one of you can take a look at this?

Also cc @jorisvandenbossche for insights about `attrs`.

(FTR, `attrs` was [proposed for deprecation](https://github.com/pandas-dev/pandas/issues/52166) but it got rejected)

**Comment by rok** [comment]
The code in question:
https://github.com/apache/arrow/blob/57f626189326251c8144d4fad89c28220c68ca75/python/pyarrow/pandas_compat.py#L278-L292
Perhaps we could allow for pickling fallback of `attributes` if json cannot serialize the type? cc @rmnskb who probably thought about this more.

**Comment by pitrou** [comment]
pickling is a security risk, we shouldn't do that.

**Comment by rok** [comment]
Let's then drop any attributes that cannot be json serialized and raise a warning?

**Comment by pitrou** [comment]
Yes, I think we can do that.

**Comment by raulcd** [comment]
Is it better to have partial information on metadata or in case of not being able to serialize part of it is better to not have those at all?

As a naive developer that doesn't know how users use `attrs` and how big can they be, I would probably have gone for an all or nothing approach, serialize `attrs` as a whole if they can be serialized, otherwise don't serialize at all.

To be honest this difference on behavior, if required, can be managed with a flag.

**Comment by rmnskb** [comment]
> Let's then drop any attributes that cannot be json serialized and raise a warning?

I do agree that we should just simply drop the attributes that we couldn't serialize. I will work on the implementation.

**Comment by rmnskb** [comment]
take

**Comment by rmnskb** [comment]
> Is it better to have partial information on metadata or in case of not being able to serialize part of it is better to not have those at all?
> 
> As a naive developer that doesn't know how users use `attrs` and how big can they be, I would probably have gone for an all or nothing approach, serialize `attrs` as a whole if they can be serialized, otherwise don't serialize at all.
> 
> To be honest this difference on behavior, if required, can be managed with a flag.

How about we just try to safely convert the data to serializable format? E.g. timestamps to string? Instead of going for all or nothing approach.

**Comment by pitrou** [comment]
> How about we just try to safely convert the data to serializable format? E.g. timestamps to string?

How does deserialization work then?

**Comment by rok** [comment]
We could also have pandas specify or enforce acceptable types for attrs in [docs](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.attrs.html).

**Comment by pitrou** [comment]
@rok The focus is on fixing this regression, not on asking Pandas to fix our issue.

**Comment by rok** [comment]
> [@rok](https://github.com/rok) The focus is on fixing this regression, not on asking Pandas to fix our issue.

Definitely, I was more thinking ahead to make things more ergonomic for Pandas users.

**Comment by pitrou** [comment]
Perhaps, but I doubt that Pandas would consider it illegal or outlandish to put a timestamp in dataframe metadata (unlike, say, a socket :-)).

**Comment by rok** [comment]
You mean like an electric socket? :)

**Comment by pitrou** [comment]
That would certainly be a security risk.

**Comment by AlenkaF** [comment]
Thank you @rmnskb for jumping on this so quickly!

To help me clear things out: I would think regression is something that worked in a previous version and stopped working in the new released one. As the original PR has been added in the new 22.0.0 release as a new feature I am not sure this issue is a regression?

I do agree it needs to be fixed though! =)

**Comment by rmnskb** [comment]
> I would think regression is something that worked in a previous version and stopped working in the new released one. As the original PR has been added in the new 22.0.0 release as a new feature I am not sure this issue is a regression?

Well, one can argue that it worked previously, since it was handled on the Pandas' side. On the other hand, from the top of my head, I don't recall Pandas taking care of objects serializability as well 🤔

**Comment by pitrou** [comment]
> To help me clear things out: I would think regression is something that worked in a previous version and stopped working in the new released one.

Well, some code that used to work now raises an exception. It's a regression.

**Comment by rok** [comment]
Issue resolved by pull request 47977
https://github.com/apache/arrow/pull/47977

**Comment by AlenkaF** [comment]
> Well, some code that used to work now raises an exception. It's a regression.

Oh yes, got it! =) Thanks (and sorry for the silly question)

**Comment by axrolld** [comment]
I'm still facing the issue with ndarrays in the attrs of my dataframe.
"pandas==3.0.6"
"pyarrow==25.0.1"

Do you know if i've done something wrong ?

My df.attrs look like this :
`
{
'A': list[int], 
'B': list[int], 
'C': float,
'D': str,
'E': array
}
`
